"""De-duplication and EOL config assembly.

Moved verbatim from the original root generate_config.py.
"""

import os
from datetime import date

from .mappings import (
    _POM_PROPERTY_MAPPINGS,
    _eol_entry,
    _map_java_dep,
    _map_npm_dep,
)


def _entry_key(entry):
    """Stable de-dup key across entry shapes."""
    src = entry.get("source", "endoflife_date")
    return (
        src,
        entry.get("product"),
        entry.get("group"), entry.get("artifact"),
        entry.get("sdk"),   entry.get("major"),
        entry.get("version"),
    )


def generate_config(scan, project_name):
    """Build an EOL config dict from scan results."""
    products = []
    seen_keys = set()
    skipped_npm = []

    def add(entry, comment=None):
        if entry is None:
            return False
        if comment:
            entry.setdefault("_comment", comment)
        key = _entry_key(entry)
        if key in seen_keys:
            return False
        seen_keys.add(key)
        products.append(entry)
        return True

    # --- POM property-driven platform versions --------------------------------
    if scan["pom_properties"]:
        products.append({"_section": "=== Platforms (from POM properties) ==="})
        for props, src in scan["pom_properties"]:
            for prop_name, mapper in _POM_PROPERTY_MAPPINGS.items():
                if prop_name in props:
                    v = props[prop_name]
                    entry = mapper(v)
                    add(entry, comment=f"From {os.path.basename(src)} (<{prop_name}>{v}</{prop_name}>)")

    # --- Java/Maven dependencies ---------------------------------------------
    if scan["java"]:
        added_section = False
        for g, a, v, src, kind in scan["java"]:
            entry = _map_java_dep(g, a, v)
            if entry is None:
                continue
            if not added_section:
                products.append({"_section": "=== Java dependencies ==="})
                added_section = True
            comment = f"From {os.path.basename(src)} ({g}:{a}:{v})"
            add(entry, comment=comment)

    # --- npm dependencies ----------------------------------------------------
    if scan["node"]:
        added_section = False
        for name, v, src in scan["node"]:
            entry = _map_npm_dep(name, v)
            if entry is None:
                # Track unmapped for the user's review
                if name not in {"react-dom"}:  # known-no-mapping
                    skipped_npm.append({"name": name, "version": v, "source": os.path.basename(src)})
                continue
            if not added_section:
                products.append({"_section": "=== npm dependencies ==="})
                added_section = True
            add(entry, comment=f"From {os.path.basename(src)} ({name}@{v})")

    # --- Infer transitive platforms from detected ones -----------------------
    # Spring Boot's release train pairs each Boot minor with a Spring Security
    # minor: Boot 3.x.y -> Security 6.x.y, Boot 2.x.y -> Security 5.x.y.
    # Add the inferred entry only when not already present.
    inferred_section_added = False
    spring_boot = next(
        (p for p in products if p.get("product") == "spring-boot"),
        None,
    )
    if spring_boot:
        sb_v = spring_boot["version"]  # "3.5"
        sb_parts = sb_v.split(".")
        if len(sb_parts) == 2 and sb_parts[0] in ("2", "3") and not any(
            p.get("product") == "spring-security" for p in products
        ):
            ss_major = "6" if sb_parts[0] == "3" else "5"
            ss_v = f"{ss_major}.{sb_parts[1]}"
            if not inferred_section_added:
                products.append({"_section": "=== Inferred from Spring Boot release train ==="})
                inferred_section_added = True
            inferred_entry = _eol_entry("spring-security", ss_v, f"Spring Security {ss_v}")
            inferred_entry["_comment"] = (
                f"Auto-derived from Spring Boot {sb_v} (release train pairing). "
                f"Spring Security version is not explicitly pinned in the POMs."
            )
            add(inferred_entry)

    # --- Build config --------------------------------------------------------
    config = {
        "_comment": [
            f"EOL config for the {project_name} project.",
            f"Auto-generated by generate_config.py on {date.today()}.",
            f"Files scanned: {len(scan['files'])}.",
            f"Tracker entries: {sum(1 for p in products if not p.get('_section'))}.",
            "",
            "REVIEW THIS FILE BEFORE DEPLOYING — auto-mapping is best-effort.",
            "Common things to check:",
            "  - Java distribution (amazon-corretto vs eclipse-temurin vs oracle-jdk)",
            "  - 'Latest patch not found' warnings indicate version pins not on Maven Central",
            "  - Skipped npm packages (see _skipped_npm_packages below) need manual entries",
            "",
            "Run with:  python lambda_function.py " + f"eol_config.{project_name}.json",
        ],
        "alert_thresholds_days": [30, 60, 90],
        "notify_when": "always",
        "notifications": [
            {"type": "console"},
            {"type": "html_file", "path": f"eol_report_{project_name}.html"},
            {"type": "sns", "_comment": "topic_arn supplied via EventBridge event input (set by Terraform)"},
        ],
        "products": products,
    }

    if skipped_npm:
        config["_skipped_npm_packages"] = skipped_npm

    return config
